Title for mnhf and qc tx's
dashpay/insight-ui pull request #94
Opened 2024-09-18 11:03 UTC by owl352

# Issue 
At this moment we getting empty tx card, if tx have 6 or 7 type

# Things done
Added cards for 6 and 7 type

2024-09-20 10:20 UTC, owl352 commented
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/2d046565-4ca9-42f5-8635-c6b008f51f1b">

2024-09-20 19:17 UTC, pshenmic requested changes

2024-09-20 19:17 UTC, pshenmic commented on public/js/angularjs-all.min.js
This should not have been committed I guess

2024-09-26 17:06 UTC, shumkov requested changes

2024-09-26 17:06 UTC, shumkov commented on public/src/js/controllers/transactions.js
> +    if (tx.type !== 6 && tx.type !== 7) {
it's not gonna work when new types will be added

2024-09-26 17:13 UTC, shumkov approved these changes

2024-09-26 17:14 UTC, pshenmic approved these changes

2024-09-26 17:14 UTC, merged